--Cria o Banco
CREATE DATABASE EMPRESA

--Scripts DDL
USE EMPRESA

CREATE TABLE LOCATION (
	ID INT NOT NULL IDENTITY PRIMARY KEY,
	NAME NVARCHAR(MAX),
LATITUDE NVARCHAR(MAX) NOT NULL,
	LONGITUDE NVARCHAR(MAX) NOT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);



--Script para criação do usuario local
USE MASTER
GO
CREATE LOGIN app 
	WITH PASSWORD=N'123456', 
	DEFAULT_DATABASE=[master], 
	CHECK_EXPIRATION=OFF, 
	CHECK_POLICY=OFF
GO
USE EMPRESA
GO
CREATE USER app FOR LOGIN app
GO
USE EMPRESA
GO
EXEC sp_addrolemember N'db_owner', N'app'
GO



--Script de insercao de dados

USE EMPRESA

--Ifes Cariacica
INSERT INTO LOCATION(NAME,LATITUDE,LONGITUDE) VALUES ('CAÇAMBA 01','-20.324715','-40.3727698');
--IEMA Cariacica
INSERT INTO LOCATION(NAME,LATITUDE,LONGITUDE) VALUES ('CAÇAMBA 02','-20.330446','-40.3608367');
--Prefeitura Cariacica
INSERT INTO LOCATION(NAME,LATITUDE,LONGITUDE) VALUES ('CAÇAMBA 03','-20.3337846','-40.3804134');
--BB Campo Grande/Cariacica
INSERT INTO LOCATION(NAME,LATITUDE,LONGITUDE) VALUES ('CAÇAMBA 04','-20.3408405','-40.3831444');
--Shopping Moxuara Cariacica
INSERT INTO LOCATION(NAME,LATITUDE,LONGITUDE) VALUES ('CAÇAMBA 05','-20.3437137','-40.4020194');

--Testes
--Update CAÇAMBA 01 para a localização Estadio Kleber Andrade
UPDATE LOCATION 
SET LATITUDE = '-20.334162', LONGITUDE= '-40.3854727'
WHERE ID = '1';

--Update CAÇAMBA 01 para a localização Ifes Cariacica
UPDATE LOCATION 
SET LATITUDE = '-20.324715', LONGITUDE= '-40.3727698'
WHERE ID = '1';



SELECT * FROM LOCATION;


USE EMPRESA
--Trigger para atualização automática do campo created_at após update
CREATE TRIGGER trgAfterUpdate ON LOCATION
AFTER UPDATE 
AS
  UPDATE L set CREATED_AT=GETDATE() 
  FROM 
  LOCATION AS L 
  INNER JOIN inserted
  AS i 
  ON L.ID = i.ID;
